import type { InferInsertModel } from "drizzle-orm";
import { db } from "./db";
import { exercises, lessons } from "./schema";

type LessonInsert = InferInsertModel<typeof lessons>;
type ExerciseInsert = InferInsertModel<typeof exercises>;

const sectionLessons: LessonInsert[] = [
  {
    id: "section-1-alphabet-opt",
    title: "Subsección informativa: Alfabeto",
    description:
      "Section 1: The Basics of Hebrew Writing. Panorama del alfabeto hebreo (informativa, no evaluada).",
    order: 1,
    xpReward: 0,
  },
  {
    id: "section-1-vowels-opt",
    title: "Subsección informativa: Vocales",
    description:
      "Section 1: The Basics of Hebrew Writing. Mapa general de vocales (BBH 2.1-2.13), letras vocálicas y reglas clave (informativa, no evaluada).",
    order: 2,
    xpReward: 0,
  },
  {
    id: "section-1-syllabification-opt",
    title: "Subsección informativa: Silabificación",
    description:
      "Section 1: The Basics of Hebrew Writing. Cómo se forman sílabas hebreas de forma gradual (informativa, no evaluada).",
    order: 3,
    xpReward: 0,
  },
  {
    id: "lesson-1-1",
    title: "Lección 1: Alef-Bet esencial",
    description:
      "Section 1: The Basics of Hebrew Writing. Reconocimiento base de consonantes para iniciar la lectura.",
    order: 4,
    xpReward: 30,
  },
  {
    id: "lesson-1-2-vowels-consonants",
    title: "Lección 2: Consonantes con Vocales",
    description:
      "Deuteronomio 6:5 como base: texto consonántico y texto con vocalización (niqqud).",
    order: 5,
    xpReward: 35,
  },
  {
    id: "lesson-1-3-vowels-long",
    title: "Lección 3: Vowel Chart 1 (Long Vowels)",
    description: "Vocales largas variables: Qamets, Tsere, Holem.",
    order: 6,
    xpReward: 35,
  },
  {
    id: "lesson-1-4-vowels-short",
    title: "Lección 4: Vowel Chart 2 (Short Vowels)",
    description: "Vocales cortas: Pathach, Seghol, Hireq, Qamets Hatuf, Qibbuts.",
    order: 7,
    xpReward: 35,
  },
  {
    id: "lesson-1-5-vowels-reduced",
    title: "Lección 5: Vowel Chart 3 (Reduced)",
    description: "Vocales reducidas (hateph): Hateph Pathach, Hateph Seghol, Hateph Qamets.",
    order: 8,
    xpReward: 35,
  },
  {
    id: "lesson-1-6-vowels-summary-lsr",
    title: "Lección 6: Resumen de Vocales",
    description: "Resumen integrado de vocales largas, cortas y reducidas.",
    order: 9,
    xpReward: 30,
  },
  {
    id: "lesson-1-7-vowel-letters-he",
    title: "Lección 7: Letras Vocálicas con He",
    description: "Qamets He, Tsere He, Seghol He, Holem He. Uso al final de palabra.",
    order: 10,
    xpReward: 35,
  },
  {
    id: "lesson-1-8-vowel-letters-waw",
    title: "Lección 8: Letras Vocálicas con Waw",
    description: "Holem Waw y Shureq como vocales largas inmutables.",
    order: 11,
    xpReward: 35,
  },
  {
    id: "lesson-1-9-vowel-letters-yod",
    title: "Lección 9: Letras Vocálicas con Yod",
    description: "Tsere Yod, Seghol Yod, Hireq Yod como vocales largas inmutables.",
    order: 12,
    xpReward: 35,
  },
  {
    id: "lesson-1-10-vowel-letters-summary",
    title: "Lección 10: Resumen de Letras Vocálicas",
    description: "Panorama de vocales escritas con He, Waw y Yod.",
    order: 13,
    xpReward: 30,
  },
  {
    id: "lesson-1-11-defective-writing",
    title: "Lección 11: Escritura Defectiva",
    description: "Contraste entre escritura plena y defectiva en hebreo bíblico.",
    order: 14,
    xpReward: 35,
  },
  {
    id: "lesson-1-12-shewa",
    title: "Lección 12: Shewa",
    description: "Shewa silente y Shewa vocal: función y diferencias clave.",
    order: 15,
    xpReward: 35,
  },
  {
    id: "lesson-1-13-daghesh-forte",
    title: "Lección 13: Daghesh Forte",
    description: "Diferencia entre Daghesh Forte y Daghesh Lene; duplicación consonántica.",
    order: 16,
    xpReward: 35,
  },
  {
    id: "lesson-1-14-gutturals-resh",
    title: "Lección 14: Guturales y Resh",
    description: "Preferencias de guturales y ר: sin Daghesh Forte, sin Shewa vocal en guturales.",
    order: 17,
    xpReward: 35,
  },
  {
    id: "freq-2200-5000",
    title: "Frecuencia Bíblica Nivel 1",
    description: "Vocabulario más frecuente (2200-5000 apariciones).",
    order: 900,
    xpReward: 0,
  },
  {
    id: "freq-1000-2199",
    title: "Frecuencia Bíblica Nivel 2",
    description: "Vocabulario frecuente intermedio (1000-2199 apariciones).",
    order: 901,
    xpReward: 0,
  },
];

const sectionExercises: ExerciseInsert[] = [
  {
    id: "section-1-alphabet-opt-ex-1",
    lessonId: "section-1-alphabet-opt",
    type: "multiple-choice",
    question: "¿Qué objetivo tiene esta subsección del alfabeto?",
    correctAnswer: "Reconocer letras y su función básica",
    options: JSON.stringify([
      "Reconocer letras y su función básica",
      "Conjugar verbos en todos los tiempos",
      "Traducir poesía completa",
      "Memorizar todo el léxico del Tanaj",
    ]),
    order: 1,
  },
  {
    id: "section-1-vowels-opt-ex-1",
    lessonId: "section-1-vowels-opt",
    type: "multiple-choice",
    question: "¿Qué cubre esta subsección de vocales?",
    correctAnswer: "Cuadros vocálicos, letras vocálicas y reglas clave",
    options: JSON.stringify([
      "Cuadros vocálicos, letras vocálicas y reglas clave",
      "Solo raíces trilíteras avanzadas",
      "Solo sintaxis de cláusulas nominales",
      "Solo crítica textual",
    ]),
    order: 1,
  },
  {
    id: "section-1-syllabification-opt-ex-1",
    lessonId: "section-1-syllabification-opt",
    type: "multiple-choice",
    question: "La silabificación te ayuda principalmente a...",
    correctAnswer: "Leer con ritmo y claridad",
    options: JSON.stringify([
      "Leer con ritmo y claridad",
      "Evitar toda vocalización",
      "Eliminar preposiciones",
      "Sustituir la traducción",
    ]),
    order: 1,
  },
  {
    id: "lesson-1-1-ex-1",
    lessonId: "lesson-1-1",
    type: "multiple-choice",
    question: "Selecciona la letra Alef",
    correctAnswer: "א",
    options: JSON.stringify(["א", "ה", "ע", "ח"]),
    order: 1,
  },
  {
    id: "lesson-1-1-ex-2",
    lessonId: "lesson-1-1",
    type: "multiple-choice",
    question: "Selecciona la letra Bet",
    correctAnswer: "ב",
    options: JSON.stringify(["ב", "כ", "מ", "נ"]),
    order: 2,
  },
  {
    id: "lesson-1-1-ex-3",
    lessonId: "lesson-1-1",
    type: "multiple-choice",
    question: "Selecciona la letra Guimel",
    correctAnswer: "ג",
    options: JSON.stringify(["ג", "ד", "ר", "ז"]),
    order: 3,
  },
  {
    id: "lesson-1-1-ex-4",
    lessonId: "lesson-1-1",
    type: "multiple-choice",
    question: "¿Qué letra suele ser silenciosa y porta vocal?",
    correctAnswer: "א",
    options: JSON.stringify(["א", "ת", "ל", "ס"]),
    order: 4,
  },
  {
    id: "lesson-1-1-ex-5",
    lessonId: "lesson-1-1",
    type: "multiple-choice",
    question: "Elige la letra que corresponde a la transliteración 'd'",
    correctAnswer: "ד",
    options: JSON.stringify(["ד", "ג", "ר", "ן"]),
    order: 5,
  },
  {
    id: "lesson-1-1-ex-6",
    lessonId: "lesson-1-1",
    type: "multiple-choice",
    question: "¿Cuál de estas es una consonante del Alef-Bet?",
    correctAnswer: "ל",
    options: JSON.stringify(["ל", "á", "é", "ó"]),
    order: 6,
  },
  {
    id: "lesson-1-2-vowels-consonants-ex-1",
    lessonId: "lesson-1-2-vowels-consonants",
    type: "multiple-choice",
    question: "¿Cuál línea muestra Deuteronomio 6:5 con vocalización (niqqud)?",
    correctAnswer: "וְאָהַבְתָּ אֵת יְהוָה אֱלֹהֶיךָ בְּכָל לְבָבְךָ",
    options: JSON.stringify([
      "וְאָהַבְתָּ אֵת יְהוָה אֱלֹהֶיךָ בְּכָל לְבָבְךָ",
      "ואהבת את יהוה אלהיך בכל לבבך",
      "וְאהבת את יהוה אלהיך בכל לבבך",
      "ואהבת אֵת יהוה אלהיך בכל לבבך",
    ]),
    order: 1,
  },
  {
    id: "lesson-1-2-vowels-consonants-ex-2",
    lessonId: "lesson-1-2-vowels-consonants",
    type: "multiple-choice",
    question: "¿Cuál es la versión consonántica sin vocales?",
    correctAnswer: "ואהבת את יהוה אלהיך בכל לבבך",
    options: JSON.stringify([
      "ואהבת את יהוה אלהיך בכל לבבך",
      "וְאָהַבְתָּ אֵת יְהוָה אֱלֹהֶיךָ בְּכָל לְבָבְךָ",
      "וְאָהַבְתָּ אֵת יְהוָה אלהיך בְּכָל לְבָבְךָ",
      "ואהבת אֵת יהוה אֱלֹהֶיךָ בכל לבבך",
    ]),
    order: 2,
  },
  {
    id: "lesson-1-2-vowels-consonants-ex-3",
    lessonId: "lesson-1-2-vowels-consonants",
    type: "multiple-choice",
    question: "La vocalización (niqqud) ayuda principalmente a...",
    correctAnswer: "Guiar la pronunciación precisa",
    options: JSON.stringify([
      "Guiar la pronunciación precisa",
      "Eliminar consonantes de la palabra",
      "Sustituir el texto consonántico",
      "Quitar toda ambigüedad semántica",
    ]),
    order: 3,
  },
  {
    id: "lesson-1-3-vowels-long-ex-1",
    lessonId: "lesson-1-3-vowels-long",
    type: "multiple-choice",
    question: "¿Qué vocal larga corresponde al sonido tipo 'a' (father)?",
    correctAnswer: "Qamets (ָ)",
    options: JSON.stringify(["Qamets (ָ)", "Pathach (ַ)", "Seghol (ֶ)", "Qibbuts (ֻ)"]),
    order: 1,
  },
  {
    id: "lesson-1-3-vowels-long-ex-2",
    lessonId: "lesson-1-3-vowels-long",
    type: "multiple-choice",
    question: "Tsere (ֵ) se asocia con pronunciación...",
    correctAnswer: "e como en 'they'",
    options: JSON.stringify([
      "e como en 'they'",
      "a como en 'bat'",
      "o como en 'bottle'",
      "u como en 'ruler'",
    ]),
    order: 2,
  },
  {
    id: "lesson-1-3-vowels-long-ex-3",
    lessonId: "lesson-1-3-vowels-long",
    type: "multiple-choice",
    question: "¿Cuál de estas es la vocal larga tipo 'o'?",
    correctAnswer: "Holem (ֹ)",
    options: JSON.stringify(["Holem (ֹ)", "Hireq (ִ)", "Seghol (ֶ)", "Hateph Pathach (ֲ)"]),
    order: 3,
  },
  {
    id: "lesson-1-4-vowels-short-ex-1",
    lessonId: "lesson-1-4-vowels-short",
    type: "multiple-choice",
    question: "Pathach (ַ) representa típicamente...",
    correctAnswer: "a corta",
    options: JSON.stringify(["a corta", "e larga", "o larga", "u larga"]),
    order: 1,
  },
  {
    id: "lesson-1-4-vowels-short-ex-2",
    lessonId: "lesson-1-4-vowels-short",
    type: "multiple-choice",
    question: "¿Qué vocal corta da sonido tipo 'i' (bitter)?",
    correctAnswer: "Hireq (ִ)",
    options: JSON.stringify(["Hireq (ִ)", "Tsere (ֵ)", "Qamets (ָ)", "Holem (ֹ)"]),
    order: 2,
  },
  {
    id: "lesson-1-4-vowels-short-ex-3",
    lessonId: "lesson-1-4-vowels-short",
    type: "multiple-choice",
    question: "¿Cuál par corresponde a vocales cortas tipo 'o' y 'u'?",
    correctAnswer: "Qamets Hatuf (ָ) y Qibbuts (ֻ)",
    options: JSON.stringify([
      "Qamets Hatuf (ָ) y Qibbuts (ֻ)",
      "Holem (ֹ) y Shureq (וּ)",
      "Tsere (ֵ) y Seghol (ֶ)",
      "Qamets (ָ) y Tsere (ֵ)",
    ]),
    order: 3,
  },
  {
    id: "lesson-1-5-vowels-reduced-ex-1",
    lessonId: "lesson-1-5-vowels-reduced",
    type: "multiple-choice",
    question: "¿Qué vocal reducida corresponde al tipo 'a'?",
    correctAnswer: "Hateph Pathach (ֲ)",
    options: JSON.stringify([
      "Hateph Pathach (ֲ)",
      "Hateph Seghol (ֱ)",
      "Hateph Qamets (ֳ)",
      "Qibbuts (ֻ)",
    ]),
    order: 1,
  },
  {
    id: "lesson-1-5-vowels-reduced-ex-2",
    lessonId: "lesson-1-5-vowels-reduced",
    type: "multiple-choice",
    question: "Hateph Seghol (ֱ) se asocia con sonido tipo...",
    correctAnswer: "e reducida",
    options: JSON.stringify(["e reducida", "a larga", "i larga", "u larga"]),
    order: 2,
  },
  {
    id: "lesson-1-6-vowels-summary-lsr-ex-1",
    lessonId: "lesson-1-6-vowels-summary-lsr",
    type: "multiple-choice",
    question: "¿Cuál triada presenta a, e, o en versión larga?",
    correctAnswer: "Qamets, Tsere, Holem",
    options: JSON.stringify([
      "Qamets, Tsere, Holem",
      "Pathach, Seghol, Hireq",
      "Hateph Pathach, Hateph Seghol, Hateph Qamets",
      "Qamets Hatuf, Qibbuts, Hireq",
    ]),
    order: 1,
  },
  {
    id: "lesson-1-6-vowels-summary-lsr-ex-2",
    lessonId: "lesson-1-6-vowels-summary-lsr",
    type: "multiple-choice",
    question: "Las vocales reducidas del resumen son...",
    correctAnswer: "Hateph Pathach, Hateph Seghol y Hateph Qamets",
    options: JSON.stringify([
      "Hateph Pathach, Hateph Seghol y Hateph Qamets",
      "Pathach, Seghol y Hireq",
      "Qamets, Tsere y Holem",
      "Holem Waw, Shureq y Hireq Yod",
    ]),
    order: 2,
  },
  {
    id: "lesson-1-7-vowel-letters-he-ex-1",
    lessonId: "lesson-1-7-vowel-letters-he",
    type: "multiple-choice",
    question: "Las vocales escritas con ה se usan típicamente...",
    correctAnswer: "Al final de una palabra",
    options: JSON.stringify([
      "Al final de una palabra",
      "Solo al inicio de palabra",
      "Solo en sílaba cerrada tónica",
      "Nunca en texto bíblico",
    ]),
    order: 1,
  },
  {
    id: "lesson-1-7-vowel-letters-he-ex-2",
    lessonId: "lesson-1-7-vowel-letters-he",
    type: "multiple-choice",
    question: "¿Cuál ejemplo pertenece al patrón con He final?",
    correctAnswer: "תּוֹרָה",
    options: JSON.stringify(["תּוֹרָה", "בּוּ", "בִּי", "בֹּו"]),
    order: 2,
  },
  {
    id: "lesson-1-8-vowel-letters-waw-ex-1",
    lessonId: "lesson-1-8-vowel-letters-waw",
    type: "multiple-choice",
    question: "¿Qué vocal con ו representa o larga?",
    correctAnswer: "Holem Waw (וֹ)",
    options: JSON.stringify(["Holem Waw (וֹ)", "Shureq (וּ)", "Hireq Yod (ִי)", "Tsere He (ֵה)"]),
    order: 1,
  },
  {
    id: "lesson-1-8-vowel-letters-waw-ex-2",
    lessonId: "lesson-1-8-vowel-letters-waw",
    type: "multiple-choice",
    question: "Shureq (וּ) se translitera usualmente como...",
    correctAnswer: "u larga",
    options: JSON.stringify(["u larga", "o breve", "e larga", "a breve"]),
    order: 2,
  },
  {
    id: "lesson-1-9-vowel-letters-yod-ex-1",
    lessonId: "lesson-1-9-vowel-letters-yod",
    type: "multiple-choice",
    question: "¿Cuál forma representa i larga con Yod?",
    correctAnswer: "Hireq Yod (ִי)",
    options: JSON.stringify([
      "Hireq Yod (ִי)",
      "Hateph Seghol (ֱ)",
      "Qamets Hatuf (ָ)",
      "Holem He (ֹה)",
    ]),
    order: 1,
  },
  {
    id: "lesson-1-9-vowel-letters-yod-ex-2",
    lessonId: "lesson-1-9-vowel-letters-yod",
    type: "multiple-choice",
    question: "Tsere Yod y Seghol Yod se asocian al tipo...",
    correctAnswer: "e",
    options: JSON.stringify(["e", "a", "o", "u"]),
    order: 2,
  },
  {
    id: "lesson-1-10-vowel-letters-summary-ex-1",
    lessonId: "lesson-1-10-vowel-letters-summary",
    type: "multiple-choice",
    question: "¿Con qué letra se escribe típicamente Shureq?",
    correctAnswer: "Waw (ו)",
    options: JSON.stringify(["Waw (ו)", "He (ה)", "Yod (י)", "Alef (א)"]),
    order: 1,
  },
  {
    id: "lesson-1-10-vowel-letters-summary-ex-2",
    lessonId: "lesson-1-10-vowel-letters-summary",
    type: "multiple-choice",
    question: "¿Cuál combinación resume bien letras vocálicas?",
    correctAnswer: "He, Waw y Yod",
    options: JSON.stringify([
      "He, Waw y Yod",
      "Bet, Gimel y Dalet",
      "Qof, Resh y Tav",
      "Nun, Samekh y Pe",
    ]),
    order: 2,
  },
  {
    id: "lesson-1-11-defective-writing-ex-1",
    lessonId: "lesson-1-11-defective-writing",
    type: "multiple-choice",
    question: "En escritura defectiva/plena, un cambio frecuente es...",
    correctAnswer: "Holem Waw -> Holem",
    options: JSON.stringify([
      "Holem Waw -> Holem",
      "Daghesh Forte -> Shewa",
      "Tsere -> Qamets Hatuf",
      "Shewa -> Qibbuts",
    ]),
    order: 1,
  },
  {
    id: "lesson-1-11-defective-writing-ex-2",
    lessonId: "lesson-1-11-defective-writing",
    type: "multiple-choice",
    question: "¿Qué par ejemplifica variación defectiva/plena de 'shofar'?",
    correctAnswer: "שֹׁפָר -> שׁוֹפָר",
    options: JSON.stringify([
      "שֹׁפָר -> שׁוֹפָר",
      "שׁוֹפָר -> שָׁפָר",
      "שֹׁפָר -> שׁוּפָר",
      "שׁוֹפָר -> שׁוֹפֶר",
    ]),
    order: 2,
  },
  {
    id: "lesson-1-12-shewa-ex-1",
    lessonId: "lesson-1-12-shewa",
    type: "multiple-choice",
    question: "¿Cuántos tipos principales de Shewa hay en hebreo?",
    correctAnswer: "Dos: silente y vocal",
    options: JSON.stringify([
      "Dos: silente y vocal",
      "Uno: siempre vocal",
      "Tres: larga, corta y reducida",
      "Cuatro: según acento",
    ]),
    order: 1,
  },
  {
    id: "lesson-1-12-shewa-ex-2",
    lessonId: "lesson-1-12-shewa",
    type: "multiple-choice",
    question: "El Shewa no pertenece directamente a...",
    correctAnswer: "Ninguna clase vocálica a/e/i/o/u",
    options: JSON.stringify([
      "Ninguna clase vocálica a/e/i/o/u",
      "Solo la clase e",
      "Solo la clase i",
      "Solo la clase o",
    ]),
    order: 2,
  },
  {
    id: "lesson-1-13-daghesh-forte-ex-1",
    lessonId: "lesson-1-13-daghesh-forte",
    type: "multiple-choice",
    question: "¿Qué hace Daghesh Forte en una consonante?",
    correctAnswer: "Duplica la consonante",
    options: JSON.stringify([
      "Duplica la consonante",
      "La vuelve silenciosa",
      "La convierte en vocal",
      "Elimina su valor fonético",
    ]),
    order: 1,
  },
  {
    id: "lesson-1-13-daghesh-forte-ex-2",
    lessonId: "lesson-1-13-daghesh-forte",
    type: "multiple-choice",
    question: "¿Qué grupo no acepta Daghesh Forte?",
    correctAnswer: "Guturales (א ה ח ע) y ר",
    options: JSON.stringify([
      "Guturales (א ה ח ע) y ר",
      "Begadkephat solamente",
      "Sibilantes solamente",
      "Todas las consonantes lo aceptan",
    ]),
    order: 2,
  },
  {
    id: "lesson-1-14-gutturals-resh-ex-1",
    lessonId: "lesson-1-14-gutturals-resh",
    type: "multiple-choice",
    question: "¿Cuáles son las guturales principales?",
    correctAnswer: "א ה ח ע",
    options: JSON.stringify(["א ה ח ע", "ב ג ד כ", "מ נ ס צ", "ק ש ת ל"]),
    order: 1,
  },
  {
    id: "lesson-1-14-gutturals-resh-ex-2",
    lessonId: "lesson-1-14-gutturals-resh",
    type: "multiple-choice",
    question: "¿Qué preferencia vocálica suelen mostrar las guturales?",
    correctAnswer: "Preferencia por vocales tipo a",
    options: JSON.stringify([
      "Preferencia por vocales tipo a",
      "Preferencia por vocales tipo i",
      "Solo aceptan vocales reducidas tipo o",
      "No muestran preferencia",
    ]),
    order: 2,
  },
  {
    id: "freq1-1",
    lessonId: "freq-2200-5000",
    type: "translation",
    question: "¿Qué significa 'אֵת'?",
    correctAnswer: "marcador del objeto directo",
    options: JSON.stringify([
      "marcador del objeto directo",
      "rey",
      "casa",
      "pueblo",
    ]),
    hebrewText: "אֵת",
    order: 1,
  },
  {
    id: "freq1-2",
    lessonId: "freq-2200-5000",
    type: "translation",
    question: "¿Qué significa 'וְ'?",
    correctAnswer: "y",
    options: JSON.stringify(["y", "pero", "porque", "sobre"]),
    hebrewText: "וְ",
    order: 2,
  },
  {
    id: "freq1-3",
    lessonId: "freq-2200-5000",
    type: "translation",
    question: "¿Qué significa 'בְּ'?",
    correctAnswer: "en",
    options: JSON.stringify(["en", "con", "desde", "sin"]),
    hebrewText: "בְּ",
    order: 3,
  },
  {
    id: "freq1-4",
    lessonId: "freq-2200-5000",
    type: "translation",
    question: "¿Qué significa 'לֹא'?",
    correctAnswer: "no",
    options: JSON.stringify(["no", "sí", "ya", "todavía"]),
    hebrewText: "לֹא",
    order: 4,
  },
  {
    id: "freq1-5",
    lessonId: "freq-2200-5000",
    type: "translation",
    question: "¿Qué significa 'עַל'?",
    correctAnswer: "sobre",
    options: JSON.stringify(["sobre", "debajo", "entre", "cerca"]),
    hebrewText: "עַל",
    order: 5,
  },
  {
    id: "freq2-1",
    lessonId: "freq-1000-2199",
    type: "translation",
    question: "¿Qué significa 'מֶלֶךְ'?",
    correctAnswer: "rey",
    options: JSON.stringify(["rey", "siervo", "profeta", "sacerdote"]),
    hebrewText: "מֶלֶךְ",
    order: 1,
  },
  {
    id: "freq2-2",
    lessonId: "freq-1000-2199",
    type: "translation",
    question: "¿Qué significa 'אִשָּׁה'?",
    correctAnswer: "mujer",
    options: JSON.stringify(["mujer", "hija", "ciudad", "ley"]),
    hebrewText: "אִשָּׁה",
    order: 2,
  },
  {
    id: "freq2-3",
    lessonId: "freq-1000-2199",
    type: "translation",
    question: "¿Qué significa 'שָׁמַע'?",
    correctAnswer: "escuchar",
    options: JSON.stringify(["escuchar", "ver", "escribir", "guardar"]),
    hebrewText: "שָׁמַע",
    order: 3,
  },
  {
    id: "freq2-4",
    lessonId: "freq-1000-2199",
    type: "translation",
    question: "¿Qué significa 'דָּבָר'?",
    correctAnswer: "palabra / asunto",
    options: JSON.stringify([
      "palabra / asunto",
      "camino",
      "luz",
      "agua",
    ]),
    hebrewText: "דָּבָר",
    order: 4,
  },
  {
    id: "freq2-5",
    lessonId: "freq-1000-2199",
    type: "translation",
    question: "¿Qué significa 'יָד'?",
    correctAnswer: "mano",
    options: JSON.stringify(["mano", "pie", "ojo", "voz"]),
    hebrewText: "יָד",
    order: 5,
  },
];

export async function seedLessonsAndExercises(database: typeof db) {
  console.log("📘 Reiniciando plan de lecciones (módulo dedicado)...");

  await database.delete(exercises);
  await database.delete(lessons);

  await database.insert(lessons).values(sectionLessons);
  await database.insert(exercises).values(sectionExercises);

  console.log(
    `✅ Lecciones sembradas desde módulo dedicado: ${sectionLessons.length} lecciones, ${sectionExercises.length} ejercicios`
  );
}
