import type { InferInsertModel } from "drizzle-orm";
import { db } from "./db";
import { exercises, lessons } from "./schema";

type LessonInsert = InferInsertModel<typeof lessons>;
type ExerciseInsert = InferInsertModel<typeof exercises>;

const sectionLessons: LessonInsert[] = [
  {
    id: "section-1-alphabet-opt",
    title: "Subsección informativa: Alfabeto",
    description:
      "Section 1: The Basics of Hebrew Writing. Panorama del alfabeto hebreo (informativa, no evaluada).",
    order: 1,
    xpReward: 0,
  },
  {
    id: "section-1-vowels-opt",
    title: "Subsección informativa: Vocales",
    description:
      "Section 1: The Basics of Hebrew Writing. Mapa general de vocales (BBH 2.1-2.13), letras vocálicas y reglas clave (informativa, no evaluada).",
    order: 2,
    xpReward: 0,
  },
  {
    id: "section-1-syllabification-opt",
    title: "Subsección informativa: Silabificación",
    description:
      "Section 1: The Basics of Hebrew Writing. Cómo se forman sílabas hebreas de forma gradual (informativa, no evaluada).",
    order: 3,
    xpReward: 0,
  },
  {
    id: "lesson-1-1",
    title: "Lección 1: Alef-Bet esencial",
    description:
      "Section 1: The Basics of Hebrew Writing. Reconocimiento base de consonantes para iniciar la lectura.",
    order: 4,
    xpReward: 30,
  },
  {
    id: "lesson-1-2-vowels-consonants",
    title: "Lección 14: Lectura Integrada (Deuteronomio 6:5)",
    description:
      "Aplicación final: lectura de texto consonántico y texto vocalizado después de dominar los cuadros vocálicos.",
    order: 17,
    xpReward: 35,
  },
  {
    id: "lesson-1-3-vowels-long",
    title: "Lección 2: Vowel Chart 1 (Long Vowels)",
    description: "Vocales largas variables: Qamets, Tsere, Holem.",
    order: 5,
    xpReward: 35,
  },
  {
    id: "lesson-1-4-vowels-short",
    title: "Lección 3: Vowel Chart 2 (Short Vowels)",
    description: "Vocales cortas: Pathach, Seghol, Hireq, Qamets Hatuf, Qibbuts.",
    order: 6,
    xpReward: 35,
  },
  {
    id: "lesson-1-5-vowels-reduced",
    title: "Lección 4: Vowel Chart 3 (Reduced)",
    description: "Vocales reducidas (hateph): Hateph Pathach, Hateph Seghol, Hateph Qamets.",
    order: 7,
    xpReward: 35,
  },
  {
    id: "lesson-1-6-vowels-summary-lsr",
    title: "Lección 5: Resumen de Vocales",
    description: "Resumen integrado de vocales largas, cortas y reducidas.",
    order: 8,
    xpReward: 30,
  },
  {
    id: "lesson-1-7-vowel-letters-he",
    title: "Lección 6: Letras Vocálicas con He",
    description: "Qamets He, Tsere He, Seghol He, Holem He. Uso al final de palabra.",
    order: 9,
    xpReward: 35,
  },
  {
    id: "lesson-1-8-vowel-letters-waw",
    title: "Lección 7: Letras Vocálicas con Waw",
    description: "Holem Waw y Shureq como vocales largas inmutables.",
    order: 10,
    xpReward: 35,
  },
  {
    id: "lesson-1-9-vowel-letters-yod",
    title: "Lección 8: Letras Vocálicas con Yod",
    description: "Tsere Yod, Seghol Yod, Hireq Yod como vocales largas inmutables.",
    order: 11,
    xpReward: 35,
  },
  {
    id: "lesson-1-10-vowel-letters-summary",
    title: "Lección 9: Resumen de Letras Vocálicas",
    description: "Panorama de vocales escritas con He, Waw y Yod.",
    order: 12,
    xpReward: 30,
  },
  {
    id: "lesson-1-11-defective-writing",
    title: "Lección 10: Escritura Defectiva",
    description: "Contraste entre escritura plena y defectiva en hebreo bíblico.",
    order: 13,
    xpReward: 35,
  },
  {
    id: "lesson-1-12-shewa",
    title: "Lección 11: Shewa",
    description: "Shewa silente y Shewa vocal: función y diferencias clave.",
    order: 14,
    xpReward: 35,
  },
  {
    id: "lesson-1-13-daghesh-forte",
    title: "Lección 12: Daghesh Forte",
    description: "Diferencia entre Daghesh Forte y Daghesh Lene; duplicación consonántica.",
    order: 15,
    xpReward: 35,
  },
  {
    id: "lesson-1-14-gutturals-resh",
    title: "Lección 13: Guturales y Resh",
    description: "Preferencias de guturales y ר: sin Daghesh Forte, sin Shewa vocal en guturales.",
    order: 16,
    xpReward: 35,
  },
  {
    id: "freq-2200-5000",
    title: "Frecuencia Bíblica Nivel 1",
    description: "Vocabulario más frecuente (2200-5000 apariciones).",
    order: 900,
    xpReward: 0,
  },
  {
    id: "freq-1000-2199",
    title: "Frecuencia Bíblica Nivel 2",
    description: "Vocabulario frecuente intermedio (1000-2199 apariciones).",
    order: 901,
    xpReward: 0,
  },
  {
    id: "practice-nouns",
    title: "Clasificación Morfológica",
    description: "Analiza sustantivos por su género, número y significado.",
    order: 902,
    xpReward: 0,
  },
];

const alphabetCoreConsonants = [
  { name: "Alef", char: "א", options: ["א", "ה", "ע", "ח"] },
  { name: "Bet", char: "ב", options: ["ב", "כ", "מ", "נ"] },
  { name: "Guimel", char: "ג", options: ["ג", "ד", "ר", "ז"] },
  { name: "Dalet", char: "ד", options: ["ד", "ר", "כ", "ב"] },
  { name: "He", char: "ה", options: ["ה", "ח", "א", "ע"] },
  { name: "Waw", char: "ו", options: ["ו", "ז", "י", "נ"] },
  { name: "Zayin", char: "ז", options: ["ז", "ו", "נ", "ג"] },
  { name: "Het", char: "ח", options: ["ח", "ה", "ע", "א"] },
  { name: "Tet", char: "ט", options: ["ט", "ת", "צ", "ס"] },
  { name: "Yod", char: "י", options: ["י", "ו", "נ", "ז"] },
  { name: "Kaf", char: "כ", options: ["כ", "ב", "פ", "מ"] },
  { name: "Lamed", char: "ל", options: ["ל", "ך", "ד", "ר"] },
  { name: "Mem", char: "מ", options: ["מ", "ס", "נ", "ם"] },
  { name: "Nun", char: "נ", options: ["נ", "ו", "ז", "ן"] },
  { name: "Samekh", char: "ס", options: ["ס", "ש", "ם", "מ"] },
  { name: "Ayin", char: "ע", options: ["ע", "א", "ה", "ח"] },
  { name: "Pe", char: "פ", options: ["פ", "ב", "כ", "ף"] },
  { name: "Tsade", char: "צ", options: ["צ", "ט", "ץ", "ס"] },
  { name: "Qof", char: "ק", options: ["ק", "כ", "ג", "ת"] },
  { name: "Resh", char: "ר", options: ["ר", "ד", "ל", "ו"] },
  { name: "Shin", char: "ש", options: ["ש", "ס", "צ", "ת"] },
  { name: "Tav", char: "ת", options: ["ת", "ט", "ד", "ש"] },
] as const;

const alphabetRecognitionExercises: ExerciseInsert[] = alphabetCoreConsonants.map((item, index) => ({
  id: `lesson-1-1-ex-${index + 1}`,
  lessonId: "lesson-1-1",
  type: "multiple-choice",
  question: `Selecciona la letra ${item.name}`,
  correctAnswer: item.char,
  options: JSON.stringify(item.options),
  order: index + 1,
}));

const freqLevel1Vocabulary = [
  { h: "אֶל", s: "hacia", o: ["hacia", "sobre", "con", "en"] },
  { h: "אֱלֹהִים", s: "Dios", o: ["Dios", "Señor", "Rey", "Hombre"] },
  { h: "אָמַר", s: "decir", o: ["decir", "hacer", "ir", "escuchar"] },
  { h: "אֶרֶץ", s: "tierra", o: ["tierra", "cielo", "ciudad", "casa"] },
  { h: "אֲשֶׁר", s: "que, el cual", o: ["que, el cual", "como", "porque", "no"] },
  { h: "אֵת", s: "señal de acusativo", o: ["señal de acusativo", "con", "hacia", "sobre"] },
  { h: "אֵת", s: "con", o: ["con", "hacia", "en", "como"] },
  { h: "בְּ", s: "en", o: ["en", "con", "hacia", "sobre"] },
  { h: "בּוֹא", s: "venir, entrar", o: ["venir, entrar", "salir", "ir", "volver"] },
  { h: "בֵּן", s: "hijo", o: ["hijo", "padre", "hermano", "rey"] },
  { h: "הַ", s: "el, la", o: ["el, la", "un, una", "este, esta", "y, también"] },
  { h: "הֲ", s: "partícula interrogativa", o: ["partícula interrogativa", "el, la", "que, el cual", "no"] },
  { h: "הָיָה", s: "ser, estar", o: ["ser, estar", "hacer", "decir", "ir"] },
  { h: "וְ", s: "y, también", o: ["y, también", "en", "como", "no"] },
  { h: "יְהוָה", s: "el Señor", o: ["el Señor", "Dios", "rey", "profeta"] },
  { h: "יוֹם", s: "día", o: ["día", "noche", "año", "tierra"] },
  { h: "יִשְׂרָאֵל", s: "Israel", o: ["Israel", "Judá", "Jerusalén", "Egipto"] },
  { h: "כְּ", s: "como", o: ["como", "en", "y", "no"] },
  { h: "כִּי", s: "porque, cuando", o: ["porque, cuando", "como", "no", "el cual"] },
  { h: "כֹּל", s: "todo, cada", o: ["todo, cada", "nada", "alguno", "mucho"] },
  { h: "לְ", s: "a, para", o: ["a, para", "en", "con", "como"] },
  { h: "לֹא", s: "no", o: ["no", "sí", "y", "porque"] },
  { h: "מֶלֶךְ", s: "rey", o: ["rey", "siervo", "sacerdote", "profeta"] },
  { h: "עַל", s: "sobre, contra", o: ["sobre, contra", "en", "hacia", "con"] },
  { h: "עָשָׂה", s: "hacer", o: ["hacer", "decir", "ir", "ser"] },
] as const;

const freqLevel2Vocabulary = [
  { h: "אָב", s: "padre", o: ["padre", "hijo", "hermano", "madre"] },
  { h: "אִישׁ", s: "hombre, marido", o: ["hombre, marido", "mujer", "niño", "rey"] },
  { h: "אִם", s: "si, cuando", o: ["si, cuando", "porque", "no", "y"] },
  { h: "אֲנִי", s: "yo", o: ["yo", "tú", "él", "nosotros"] },
  { h: "בַּיִת", s: "casa", o: ["casa", "ciudad", "tierra", "templo"] },
  { h: "דָּבָר", s: "palabra, cosa", o: ["palabra, cosa", "voz", "libro", "ley"] },
  { h: "דָּבַר", s: "hablar", o: ["hablar", "decir", "escuchar", "ver"] },
  { h: "דָּוִד", s: "David", o: ["David", "Moisés", "Salomón", "Samuel"] },
  { h: "הוּא", s: "él", o: ["él", "ella", "yo", "tú"] },
  { h: "הָלַך", s: "ir, caminar", o: ["ir, caminar", "venir", "sentarse", "volver"] },
  { h: "הֵנָּה | הֵמָּה", s: "ellos, ellas", o: ["ellos, ellas", "nosotros", "vocales", "hombres"] },
  { h: "הִנֵּה", s: "he aquí", o: ["he aquí", "allí", "dónde", "cómo"] },
  { h: "זֹאת | זֶה", s: "este, esta", o: ["este, esta", "ese, aquel", "él, ella", "todo"] },
  { h: "יָד", s: "mano", o: ["mano", "pie", "cabeza", "ojo"] },
  { h: "יָצָא", s: "salir", o: ["salir", "entrar", "venir", "volver"] },
  { h: "יָשַׁב", s: "sentarse, habitar", o: ["sentarse, habitar", "caminar", "estar de pie", "ir"] },
  { h: "לִפְנֵי", s: "delante de", o: ["delante de", "detrás de", "sobre", "debajo de"] },
  { h: "מִן", s: "de, desde", o: ["de, desde", "en", "para", "con"] },
  { h: "נָתַן", s: "dar", o: ["dar", "tomar", "hacer", "decir"] },
  { h: "עַד", s: "hasta que, mientras", o: ["hasta que, mientras", "desde", "sobre", "porque"] },
  { h: "עִיר", s: "ciudad", o: ["ciudad", "pueblo", "casa", "tierra"] },
  { h: "עַם", s: "pueblo", o: ["pueblo", "nación", "multitud", "hombres"] },
  { h: "עִם", s: "con", o: ["con", "sin", "en", "sobre"] },
  { h: "פָּנִים | פָּנֶה", s: "cara", o: ["cara", "mano", "cabeza", "boca"] },
  { h: "רָאָה", s: "ver", o: ["ver", "oír", "hablar", "conocer"] },
  { h: "שׁוּב", s: "volver", o: ["volver", "salir", "ir", "venir"] },
  { h: "שָׁמַע", s: "oír, escuchar", o: ["oír, escuchar", "ver", "hablar", "decir"] },
] as const;

const freqLevel1Exercises: ExerciseInsert[] = freqLevel1Vocabulary.map((v, i) => ({
  id: `freq1-${i + 1}`,
  lessonId: "freq-2200-5000",
  type: "translation",
  question: `¿Qué significa '${v.h}'?`,
  correctAnswer: v.s,
  options: JSON.stringify(v.o),
  hebrewText: v.h,
  order: i + 1,
}));

const freqLevel2Exercises: ExerciseInsert[] = freqLevel2Vocabulary.map((v, i) => ({
  id: `freq2-${i + 1}`,
  lessonId: "freq-1000-2199",
  type: "translation",
  question: `¿Qué significa '${v.h}'?`,
  correctAnswer: v.s,
  options: JSON.stringify(v.o),
  hebrewText: v.h,
  order: i + 1,
}));

const nounsPracticeVocabulary = [
  { h: "דָּבָר", g: "m", n: "s", m: "palabra / cosa", d: ["día", "reyes", "hijas"] },
  { h: "יוֹם", g: "m", n: "s", m: "día", d: ["dos días", "reyes", "muro"] },
  { h: "יָדַיִם", g: "f", n: "d", m: "manos", d: ["dos días", "pies", "leyes"] },
  { h: "מְלָכִים", g: "m", n: "p", m: "reyes", d: ["hijas", "leyes", "niños"] },
  { h: "בָּנוֹת", g: "f", n: "p", m: "hijas", d: ["hija", "leyes", "reyes"] },
  { h: "תּוֹרוֹת", g: "f", n: "p", m: "leyes", d: ["hijas", "reyes", "manos"] },
  { h: "חוֹמָה", g: "f", n: "s", m: "muro", d: ["arco", "día", "palabra / cosa"] },
  { h: "קֶשֶׁת", g: "f", n: "s", m: "arco", d: ["muro", "hija", "leyes"] },
  { h: "יוֹמַיִם", g: "m", n: "d", m: "dos días", d: ["día", "manos", "pies"] },
  { h: "רַגְלַיִם", g: "f", n: "d", m: "pies", d: ["manos", "dos días", "hijas"] },
] as const;

const nounsPracticeExercises: ExerciseInsert[] = nounsPracticeVocabulary.map((entry, index) => ({
  id: `noun-p-${index + 1}`,
  lessonId: "practice-nouns",
  type: "noun-parsing",
  question: "Clasifica este sustantivo hebreo",
  correctAnswer: JSON.stringify({
    gender: entry.g,
    number: entry.n,
    meaning: entry.m,
  }),
  options: JSON.stringify([entry.m, ...entry.d]),
  hebrewText: entry.h,
  order: index + 1,
}));

const sectionExercises: ExerciseInsert[] = [
  {
    id: "section-1-alphabet-opt-ex-1",
    lessonId: "section-1-alphabet-opt",
    type: "multiple-choice",
    question: "¿Qué objetivo tiene esta subsección del alfabeto?",
    correctAnswer: "Reconocer letras y su función básica",
    options: JSON.stringify([
      "Reconocer letras y su función básica",
      "Conjugar verbos en todos los tiempos",
      "Traducir poesía completa",
      "Memorizar todo el léxico del Tanaj",
    ]),
    order: 1,
  },
  {
    id: "section-1-vowels-opt-ex-1",
    lessonId: "section-1-vowels-opt",
    type: "multiple-choice",
    question: "¿Qué cubre esta subsección de vocales?",
    correctAnswer: "Cuadros vocálicos, letras vocálicas y reglas clave",
    options: JSON.stringify([
      "Cuadros vocálicos, letras vocálicas y reglas clave",
      "Solo raíces trilíteras avanzadas",
      "Solo sintaxis de cláusulas nominales",
      "Solo crítica textual",
    ]),
    order: 1,
  },
  {
    id: "section-1-syllabification-opt-ex-1",
    lessonId: "section-1-syllabification-opt",
    type: "multiple-choice",
    question: "La silabificación te ayuda principalmente a...",
    correctAnswer: "Leer con ritmo y claridad",
    options: JSON.stringify([
      "Leer con ritmo y claridad",
      "Evitar toda vocalización",
      "Eliminar preposiciones",
      "Sustituir la traducción",
    ]),
    order: 1,
  },
  ...alphabetRecognitionExercises,
  {
    id: "lesson-1-2-vowels-consonants-ex-1",
    lessonId: "lesson-1-2-vowels-consonants",
    type: "multiple-choice",
    question: "¿Cuál línea muestra Deuteronomio 6:5 con vocalización (niqqud)?",
    correctAnswer: "וְאָהַבְתָּ אֵת יְהוָה אֱלֹהֶיךָ בְּכָל לְבָבְךָ",
    options: JSON.stringify([
      "וְאָהַבְתָּ אֵת יְהוָה אֱלֹהֶיךָ בְּכָל לְבָבְךָ",
      "ואהבת את יהוה אלהיך בכל לבבך",
      "וְאהבת את יהוה אלהיך בכל לבבך",
      "ואהבת אֵת יהוה אלהיך בכל לבבך",
    ]),
    order: 1,
  },
  {
    id: "lesson-1-2-vowels-consonants-ex-2",
    lessonId: "lesson-1-2-vowels-consonants",
    type: "multiple-choice",
    question: "¿Cuál es la versión consonántica sin vocales?",
    correctAnswer: "ואהבת את יהוה אלהיך בכל לבבך",
    options: JSON.stringify([
      "ואהבת את יהוה אלהיך בכל לבבך",
      "וְאָהַבְתָּ אֵת יְהוָה אֱלֹהֶיךָ בְּכָל לְבָבְךָ",
      "וְאָהַבְתָּ אֵת יְהוָה אלהיך בְּכָל לְבָבְךָ",
      "ואהבת אֵת יהוה אֱלֹהֶיךָ בכל לבבך",
    ]),
    order: 2,
  },
  {
    id: "lesson-1-2-vowels-consonants-ex-3",
    lessonId: "lesson-1-2-vowels-consonants",
    type: "multiple-choice",
    question: "La vocalización (niqqud) ayuda principalmente a...",
    correctAnswer: "Guiar la pronunciación precisa",
    options: JSON.stringify([
      "Guiar la pronunciación precisa",
      "Eliminar consonantes de la palabra",
      "Sustituir el texto consonántico",
      "Quitar toda ambigüedad semántica",
    ]),
    order: 3,
  },
  {
    id: "lesson-1-3-vowels-long-ex-1",
    lessonId: "lesson-1-3-vowels-long",
    type: "multiple-choice",
    question: "¿Qué vocal larga corresponde al sonido tipo 'a' (father)?",
    correctAnswer: "Qamets (ָ)",
    options: JSON.stringify(["Qamets (ָ)", "Pathach (ַ)", "Seghol (ֶ)", "Qibbuts (ֻ)"]),
    order: 1,
  },
  {
    id: "lesson-1-3-vowels-long-ex-2",
    lessonId: "lesson-1-3-vowels-long",
    type: "multiple-choice",
    question: "Tsere (ֵ) se asocia con pronunciación...",
    correctAnswer: "e como en 'they'",
    options: JSON.stringify([
      "e como en 'they'",
      "a como en 'bat'",
      "o como en 'bottle'",
      "u como en 'ruler'",
    ]),
    order: 2,
  },
  {
    id: "lesson-1-3-vowels-long-ex-3",
    lessonId: "lesson-1-3-vowels-long",
    type: "multiple-choice",
    question: "¿Cuál de estas es la vocal larga tipo 'o'?",
    correctAnswer: "Holem (ֹ)",
    options: JSON.stringify(["Holem (ֹ)", "Hireq (ִ)", "Seghol (ֶ)", "Hateph Pathach (ֲ)"]),
    order: 3,
  },
  {
    id: "lesson-1-4-vowels-short-ex-1",
    lessonId: "lesson-1-4-vowels-short",
    type: "multiple-choice",
    question: "Pathach (ַ) representa típicamente...",
    correctAnswer: "a corta",
    options: JSON.stringify(["a corta", "e larga", "o larga", "u larga"]),
    order: 1,
  },
  {
    id: "lesson-1-4-vowels-short-ex-2",
    lessonId: "lesson-1-4-vowels-short",
    type: "multiple-choice",
    question: "¿Qué vocal corta da sonido tipo 'i' (bitter)?",
    correctAnswer: "Hireq (ִ)",
    options: JSON.stringify(["Hireq (ִ)", "Tsere (ֵ)", "Qamets (ָ)", "Holem (ֹ)"]),
    order: 2,
  },
  {
    id: "lesson-1-4-vowels-short-ex-3",
    lessonId: "lesson-1-4-vowels-short",
    type: "multiple-choice",
    question: "¿Cuál par corresponde a vocales cortas tipo 'o' y 'u'?",
    correctAnswer: "Qamets Hatuf (ָ) y Qibbuts (ֻ)",
    options: JSON.stringify([
      "Qamets Hatuf (ָ) y Qibbuts (ֻ)",
      "Holem (ֹ) y Shureq (וּ)",
      "Tsere (ֵ) y Seghol (ֶ)",
      "Qamets (ָ) y Tsere (ֵ)",
    ]),
    order: 3,
  },
  {
    id: "lesson-1-5-vowels-reduced-ex-1",
    lessonId: "lesson-1-5-vowels-reduced",
    type: "multiple-choice",
    question: "¿Qué vocal reducida corresponde al tipo 'a'?",
    correctAnswer: "Hateph Pathach (ֲ)",
    options: JSON.stringify([
      "Hateph Pathach (ֲ)",
      "Hateph Seghol (ֱ)",
      "Hateph Qamets (ֳ)",
      "Qibbuts (ֻ)",
    ]),
    order: 1,
  },
  {
    id: "lesson-1-5-vowels-reduced-ex-2",
    lessonId: "lesson-1-5-vowels-reduced",
    type: "multiple-choice",
    question: "Hateph Seghol (ֱ) se asocia con sonido tipo...",
    correctAnswer: "e reducida",
    options: JSON.stringify(["e reducida", "a larga", "i larga", "u larga"]),
    order: 2,
  },
  {
    id: "lesson-1-6-vowels-summary-lsr-ex-1",
    lessonId: "lesson-1-6-vowels-summary-lsr",
    type: "multiple-choice",
    question: "¿Cuál triada presenta a, e, o en versión larga?",
    correctAnswer: "Qamets, Tsere, Holem",
    options: JSON.stringify([
      "Qamets, Tsere, Holem",
      "Pathach, Seghol, Hireq",
      "Hateph Pathach, Hateph Seghol, Hateph Qamets",
      "Qamets Hatuf, Qibbuts, Hireq",
    ]),
    order: 1,
  },
  {
    id: "lesson-1-6-vowels-summary-lsr-ex-2",
    lessonId: "lesson-1-6-vowels-summary-lsr",
    type: "multiple-choice",
    question: "Las vocales reducidas del resumen son...",
    correctAnswer: "Hateph Pathach, Hateph Seghol y Hateph Qamets",
    options: JSON.stringify([
      "Hateph Pathach, Hateph Seghol y Hateph Qamets",
      "Pathach, Seghol y Hireq",
      "Qamets, Tsere y Holem",
      "Holem Waw, Shureq y Hireq Yod",
    ]),
    order: 2,
  },
  {
    id: "lesson-1-7-vowel-letters-he-ex-1",
    lessonId: "lesson-1-7-vowel-letters-he",
    type: "multiple-choice",
    question: "Las vocales escritas con ה se usan típicamente...",
    correctAnswer: "Al final de una palabra",
    options: JSON.stringify([
      "Al final de una palabra",
      "Solo al inicio de palabra",
      "Solo en sílaba cerrada tónica",
      "Nunca en texto bíblico",
    ]),
    order: 1,
  },
  {
    id: "lesson-1-7-vowel-letters-he-ex-2",
    lessonId: "lesson-1-7-vowel-letters-he",
    type: "multiple-choice",
    question: "¿Cuál ejemplo pertenece al patrón con He final?",
    correctAnswer: "תּוֹרָה",
    options: JSON.stringify(["תּוֹרָה", "בּוּ", "בִּי", "בֹּו"]),
    order: 2,
  },
  {
    id: "lesson-1-8-vowel-letters-waw-ex-1",
    lessonId: "lesson-1-8-vowel-letters-waw",
    type: "multiple-choice",
    question: "¿Qué vocal con ו representa o larga?",
    correctAnswer: "Holem Waw (וֹ)",
    options: JSON.stringify(["Holem Waw (וֹ)", "Shureq (וּ)", "Hireq Yod (ִי)", "Tsere He (ֵה)"]),
    order: 1,
  },
  {
    id: "lesson-1-8-vowel-letters-waw-ex-2",
    lessonId: "lesson-1-8-vowel-letters-waw",
    type: "multiple-choice",
    question: "Shureq (וּ) se translitera usualmente como...",
    correctAnswer: "u larga",
    options: JSON.stringify(["u larga", "o breve", "e larga", "a breve"]),
    order: 2,
  },
  {
    id: "lesson-1-9-vowel-letters-yod-ex-1",
    lessonId: "lesson-1-9-vowel-letters-yod",
    type: "multiple-choice",
    question: "¿Cuál forma representa i larga con Yod?",
    correctAnswer: "Hireq Yod (ִי)",
    options: JSON.stringify([
      "Hireq Yod (ִי)",
      "Hateph Seghol (ֱ)",
      "Qamets Hatuf (ָ)",
      "Holem He (ֹה)",
    ]),
    order: 1,
  },
  {
    id: "lesson-1-9-vowel-letters-yod-ex-2",
    lessonId: "lesson-1-9-vowel-letters-yod",
    type: "multiple-choice",
    question: "Tsere Yod y Seghol Yod se asocian al tipo...",
    correctAnswer: "e",
    options: JSON.stringify(["e", "a", "o", "u"]),
    order: 2,
  },
  {
    id: "lesson-1-10-vowel-letters-summary-ex-1",
    lessonId: "lesson-1-10-vowel-letters-summary",
    type: "multiple-choice",
    question: "¿Con qué letra se escribe típicamente Shureq?",
    correctAnswer: "Waw (ו)",
    options: JSON.stringify(["Waw (ו)", "He (ה)", "Yod (י)", "Alef (א)"]),
    order: 1,
  },
  {
    id: "lesson-1-10-vowel-letters-summary-ex-2",
    lessonId: "lesson-1-10-vowel-letters-summary",
    type: "multiple-choice",
    question: "¿Cuál combinación resume bien letras vocálicas?",
    correctAnswer: "He, Waw y Yod",
    options: JSON.stringify([
      "He, Waw y Yod",
      "Bet, Gimel y Dalet",
      "Qof, Resh y Tav",
      "Nun, Samekh y Pe",
    ]),
    order: 2,
  },
  {
    id: "lesson-1-11-defective-writing-ex-1",
    lessonId: "lesson-1-11-defective-writing",
    type: "multiple-choice",
    question: "En escritura defectiva/plena, un cambio frecuente es...",
    correctAnswer: "Holem Waw -> Holem",
    options: JSON.stringify([
      "Holem Waw -> Holem",
      "Daghesh Forte -> Shewa",
      "Tsere -> Qamets Hatuf",
      "Shewa -> Qibbuts",
    ]),
    order: 1,
  },
  {
    id: "lesson-1-11-defective-writing-ex-2",
    lessonId: "lesson-1-11-defective-writing",
    type: "multiple-choice",
    question: "¿Qué par ejemplifica variación defectiva/plena de 'shofar'?",
    correctAnswer: "שֹׁפָר -> שׁוֹפָר",
    options: JSON.stringify([
      "שֹׁפָר -> שׁוֹפָר",
      "שׁוֹפָר -> שָׁפָר",
      "שֹׁפָר -> שׁוּפָר",
      "שׁוֹפָר -> שׁוֹפֶר",
    ]),
    order: 2,
  },
  {
    id: "lesson-1-12-shewa-ex-1",
    lessonId: "lesson-1-12-shewa",
    type: "multiple-choice",
    question: "¿Cuántos tipos principales de Shewa hay en hebreo?",
    correctAnswer: "Dos: silente y vocal",
    options: JSON.stringify([
      "Dos: silente y vocal",
      "Uno: siempre vocal",
      "Tres: larga, corta y reducida",
      "Cuatro: según acento",
    ]),
    order: 1,
  },
  {
    id: "lesson-1-12-shewa-ex-2",
    lessonId: "lesson-1-12-shewa",
    type: "multiple-choice",
    question: "El Shewa no pertenece directamente a...",
    correctAnswer: "Ninguna clase vocálica a/e/i/o/u",
    options: JSON.stringify([
      "Ninguna clase vocálica a/e/i/o/u",
      "Solo la clase e",
      "Solo la clase i",
      "Solo la clase o",
    ]),
    order: 2,
  },
  {
    id: "lesson-1-13-daghesh-forte-ex-1",
    lessonId: "lesson-1-13-daghesh-forte",
    type: "multiple-choice",
    question: "¿Qué hace Daghesh Forte en una consonante?",
    correctAnswer: "Duplica la consonante",
    options: JSON.stringify([
      "Duplica la consonante",
      "La vuelve silenciosa",
      "La convierte en vocal",
      "Elimina su valor fonético",
    ]),
    order: 1,
  },
  {
    id: "lesson-1-13-daghesh-forte-ex-2",
    lessonId: "lesson-1-13-daghesh-forte",
    type: "multiple-choice",
    question: "¿Qué grupo no acepta Daghesh Forte?",
    correctAnswer: "Guturales (א ה ח ע) y ר",
    options: JSON.stringify([
      "Guturales (א ה ח ע) y ר",
      "Begadkephat solamente",
      "Sibilantes solamente",
      "Todas las consonantes lo aceptan",
    ]),
    order: 2,
  },
  {
    id: "lesson-1-14-gutturals-resh-ex-1",
    lessonId: "lesson-1-14-gutturals-resh",
    type: "multiple-choice",
    question: "¿Cuáles son las guturales principales?",
    correctAnswer: "א ה ח ע",
    options: JSON.stringify(["א ה ח ע", "ב ג ד כ", "מ נ ס צ", "ק ש ת ל"]),
    order: 1,
  },
  {
    id: "lesson-1-14-gutturals-resh-ex-2",
    lessonId: "lesson-1-14-gutturals-resh",
    type: "multiple-choice",
    question: "¿Qué preferencia vocálica suelen mostrar las guturales?",
    correctAnswer: "Preferencia por vocales tipo a",
    options: JSON.stringify([
      "Preferencia por vocales tipo a",
      "Preferencia por vocales tipo i",
      "Solo aceptan vocales reducidas tipo o",
      "No muestran preferencia",
    ]),
    order: 2,
  },
  ...freqLevel1Exercises,
  ...freqLevel2Exercises,
  ...nounsPracticeExercises,
];

export async function seedLessonsAndExercises(database: typeof db) {
  console.log("📘 Reiniciando plan de lecciones (módulo dedicado)...");

  await database.delete(exercises);
  await database.delete(lessons);

  await database.insert(lessons).values(sectionLessons);
  await database.insert(exercises).values(sectionExercises);

  console.log(
    `✅ Lecciones sembradas desde módulo dedicado: ${sectionLessons.length} lecciones, ${sectionExercises.length} ejercicios`
  );
}
